---
baseURL: https://piko-heksagon.netlify.app/
languageCode: en-us
title: Andarduft - Explore Andarduft Content
theme: piko
paginate: "9"
copyright: A template by [Heksagon](https://www.heksagon.net)
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: andarduft
  description: "Explore insights and resources on andarduft. Your go-to source for everything related to andarduft."
  math: false
  images:
    - "/uploads/og.webp"
  label:
    title: _Andarduft - Discover More_
    text: "Welcome to the world of andarduft"
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWidth: "35"
  comments: true
  mainSections:
    - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: "We use cookies to improve your experience on our andarduft site and to show you relevant advertising."
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    disableHeroSection: false
    heroUpperTitle: Discover Andarduft
    heroTitle: "Welcome to Andarduft Insights"
    heroDescription: "Uncover valuable information and guides on andarduft."
    heroCTAPrimaryText: Explore Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Get in Touch
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/andarduft-background.webp"
    disableBlogSection: false
    blogTitle: Andarduft Articles
    blogDescription: "Read the latest articles on andarduft and related topics."
    seeMoreText: See All Articles
    disableAboutSection: false
    aboutTitle: About Andarduft
    aboutDescription: "Learn more about andarduft and our mission to provide the best resources."
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: "Welcome to the andarduft site. Here, you’ll find curated articles and insights on all things andarduft."
    disablePortfolioSection: false
    portfolioTitle: Andarduft Resources
    portfolioDescription: "Explore a range of resources dedicated to andarduft."
    portfolio:
      - imageUrl: /uploads/portfolio-1.webp
        alt: "Andarduft Resource 1"
        description: "Resource One on andarduft."
        websiteUrl: #
      - imageUrl: /uploads/portfolio-2.webp
        alt: "Andarduft Resource 2"
        description: "Resource Two on andarduft."
        websiteUrl: #
      - imageUrl: /uploads/portfolio-3.webp
        alt: "Andarduft Resource 3"
        description: "Resource Three on andarduft."
        websiteUrl: #
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "100"
    threshold: "0.3"
    minMatchCharLength: "3"
    keys:
      - title
      - permalink
      - summary
      - content
  plugins:
    css:
      - link: plugins/css/pico.min.css
    js:
      - link: plugins/js/feather.min.js
menus:
  main:
    - name: Andarduft Blog
      title: Blog
      pre: pen-tool
      url: "/blog"
      weight: "20"
    - name: Search Andarduft
      title: Search
      pre: search
      url: "/search"
      weight: "30"
    - name: Contact Us
      title: Contact
      pre: mail
      url: "/contact"
      weight: "40"
    - name: Github
      title:
      pre: github
      url: https://github.com/heksagonnet/piko
      weight: "50"
  search:
    - name: Andarduft Categories
      title: Categories
      url: "/categories"
      weight: "10"
    - name: Archives
      title: Archives
      url: "/archives"
      weight: "20"
    - name: Tags
      title: Tags
      url: "/tags"
      weight: "30"
